tellraw @s {"rawtext":[{"text":"§6==========================§r§§§bA Balanced Diet :§r§§§6==========================§r§§ "}]}
tellraw @s {"rawtext":[{"text":"§c[ INCOMPLETE ]§r"}]}
tellraw @s[tag=!Ate_Apple] {"rawtext":[{"text":"Apple"}]}
tellraw @s[tag=!Ate_Baked_potato] {"rawtext":[{"text":"Baked Potato"}]}
tellraw @s[tag=!Ate_Beetroot] {"rawtext":[{"text":"Beetroot"}]}
tellraw @s[tag=!Ate_Beetroot_soup] {"rawtext":[{"text":"Beetroot Soup"}]}
tellraw @s[tag=!Ate_Bread] {"rawtext":[{"text":"Bread"}]}
tellraw @s[tag=!Ate_Carrot] {"rawtext":[{"text":"Carrot"}]}
tellraw @s[tag=!Ate_Chorus_fruit] {"rawtext":[{"text":"Chorus Fruit"}]}
tellraw @s[tag=!Ate_Cooked_beef] {"rawtext":[{"text":"Cooked Beef"}]}
tellraw @s[tag=!Ate_Cooked_chicken] {"rawtext":[{"text":"Cooked Chicken"}]}
tellraw @s[tag=!Ate_Cooked_cod] {"rawtext":[{"text":"Cooked Cod"}]}
tellraw @s[tag=!Ate_Cooked_mutton] {"rawtext":[{"text":"Cooked Mutton"}]}
tellraw @s[tag=!Ate_Cooked_porkchop] {"rawtext":[{"text":"Cooked Porkchop"}]}
tellraw @s[tag=!Ate_Cooked_rabbit] {"rawtext":[{"text":"Cooked Rabbit"}]}
tellraw @s[tag=!Ate_Cooked_salmon] {"rawtext":[{"text":"Cooked Salmon"}]}
tellraw @s[tag=!Ate_Cookie] {"rawtext":[{"text":"Cookie"}]}
tellraw @s[tag=!Ate_Dried_kelp] {"rawtext":[{"text":"Dried Kelp"}]}
tellraw @s[tag=!Ate_Enchanted_golden_apple] {"rawtext":[{"text":"Enchanted Apple"}]}
tellraw @s[tag=!Ate_Glow_berries] {"rawtext":[{"text":"Glow Berries"}]}
tellraw @s[tag=!Ate_Golden_apple] {"rawtext":[{"text":"Golden Apple"}]}
tellraw @s[tag=!Ate_Golden_carrot] {"rawtext":[{"text":"Golden Carrot"}]}
tellraw @s[tag=!Ate_Honey_bottle] {"rawtext":[{"text":"Honey Bottle"}]}
tellraw @s[tag=!Ate_Melon_slice] {"rawtext":[{"text":"Melon Slice"}]}
tellraw @s[tag=!Ate_Mushroom_stew] {"rawtext":[{"text":"Mushroom Stew"}]}
tellraw @s[tag=!Ate_Poisonous_potato] {"rawtext":[{"text":"Poisonous Potato"}]}
tellraw @s[tag=!Ate_Potato] {"rawtext":[{"text":"Potato"}]}
tellraw @s[tag=!Ate_Pufferfish] {"rawtext":[{"text":"Pufferfish"}]}
tellraw @s[tag=!Ate_Pumpkin_pie] {"rawtext":[{"text":"Pumpkin Pie"}]}
tellraw @s[tag=!Ate_Rabbit_stew] {"rawtext":[{"text":"Rabbit Stew"}]}
tellraw @s[tag=!Ate_Beef] {"rawtext":[{"text":"Raw Beef"}]}
tellraw @s[tag=!Ate_Chicken] {"rawtext":[{"text":"Raw Chicken"}]}
tellraw @s[tag=!Ate_Cod] {"rawtext":[{"text":"Raw Cod"}]}
tellraw @s[tag=!Ate_Mutton] {"rawtext":[{"text":"Raw Mutton"}]}
tellraw @s[tag=!Ate_Porkchop] {"rawtext":[{"text":"Raw Porkchop"}]}
tellraw @s[tag=!Ate_Rabbit] {"rawtext":[{"text":"Raw Rabbit"}]}
tellraw @s[tag=!Ate_Salmon] {"rawtext":[{"text":"Raw Salmon"}]}
tellraw @s[tag=!Ate_Rotten_flesh] {"rawtext":[{"text":"Rotten Flesh"}]}
tellraw @s[tag=!Ate_Spider_eye] {"rawtext":[{"text":"Spider Eye"}]}
tellraw @s[tag=!Ate_Suspicious_stew] {"rawtext":[{"text":"Suspicious Stew"}]}
tellraw @s[tag=!Ate_Sweet_berries] {"rawtext":[{"text":"Sweet Berries"}]}
tellraw @s[tag=!Ate_Tropical_fish] {"rawtext":[{"text":"Tropical Fish"}]}