scoreboard objectives add AdvancementCount dummy
scoreboard players remove @s[scores={AdvancementCount=1..}] AdvancementCount 1
scoreboard objectives add HusbandryCount dummy
scoreboard players remove @s[scores={HusbandryCount=1..}] HusbandryCount 1
tag @s remove BalancedDiet
tag @s remove Ate_Apple
tag @s remove Ate_Baked_potato
tag @s remove Ate_Beef
tag @s remove Ate_Beetroot
tag @s remove Ate_Beetroot_soup
tag @s remove Ate_Bread
tag @s remove Ate_Carrot
tag @s remove Ate_Chicken
tag @s remove Ate_Chorus_fruit
tag @s remove Ate_Cod
tag @s remove Ate_Cooked_beef
tag @s remove Ate_Cooked_chicken
tag @s remove Ate_Cooked_cod
tag @s remove Ate_Cooked_mutton
tag @s remove Ate_Cooked_porkchop
tag @s remove Ate_Cooked_rabbit
tag @s remove Ate_Cooked_salmon
tag @s remove Ate_Cookie
tag @s remove Ate_Dried_kelp
tag @s remove Ate_Enchanted_golden_apple
tag @s remove Ate_Glow_berries
tag @s remove Ate_Golden_apple
tag @s remove Ate_Golden_carrot
tag @s remove Ate_Honey_bottle
tag @s remove Ate_Melon_slice
tag @s remove Ate_Mushroom_stew
tag @s remove Ate_Mutton
tag @s remove Ate_Poisonous_potato
tag @s remove Ate_Porkchop
tag @s remove Ate_Potato
tag @s remove Ate_Pufferfish
tag @s remove Ate_Pumpkin_pie
tag @s remove Ate_Rabbit
tag @s remove Ate_Rabbit_stew
tag @s remove Ate_Rotten_flesh
tag @s remove Ate_Salmon
tag @s remove Ate_Spider_eye
tag @s remove Ate_Suspicious_stew
tag @s remove Ate_Sweet_berries
tag @s remove Ate_Tropical_fish
tag @s remove Ate_Meal
tag @s remove Ate_Miners_stew
tag @s remove Ate_Sweet_berry_pie
tag @s remove Ate_Chorus_pie
tag @s remove Ate_Apple_pie
tag @s remove Ate_Golden_apple_pie
tag @s remove Ate_Notch_apple_pie
tag @s remove Ate_Cinnamon_roll
tag @s remove Ate_Blazing_kebab
tag @s remove Ate_Mincemeat_pie
tag @s remove Ate_Puffer_cookie
tag @s remove Ate_Sandwich_beef
tag @s remove Ate_Sandwich_chicken
tag @s remove Ate_Sandwich_fish
tag @s remove Ate_Sandwich_mutton
tag @s remove Ate_Sandwich_pork
tag @s remove Ate_Sandwich_rabbit
tag @s remove Ate_Sandwich_salmon