tag @s add Badlands
tag @s add BambooJungle
tag @s add Beach
tag @s add BirchForest
tag @s add CherryGrove
tag @s add ColdOcean
tag @s add DarkForest
tag @s add DeepColdOcean
tag @s add DeepDark
tag @s add DeepFrozenOcean
tag @s add DeepLukewarmOcean
tag @s add DeepOcean
tag @s add Desert
tag @s add DripstoneCaves
tag @s add ErodedBadlands
tag @s add FlowerForest
tag @s add Forest
tag @s add FrozenOcean
tag @s add FrozenPeaks
tag @s add FrozenRiver
tag @s add Grove
tag @s add IceSpikes
tag @s add JaggedPeaks
tag @s add Jungle
tag @s add LukewarmOcean
tag @s add LushCaves
tag @s add MangroveSwamp
tag @s add Meadow
tag @s add MushroomFields
tag @s add Ocean
tag @s add OldGrowthBirchForest
tag @s add OldGrowthPineTaiga
tag @s add OldGrowthSpruceTaiga
tag @s add PaleGarden
tag @s add Plains
tag @s add River
tag @s add Savanna
tag @s add SavannaPlateau
tag @s add SnowyBeach
tag @s add SnowyPlains
tag @s add SnowySlopes
tag @s add SnowyTaiga
tag @s add SparseJungle
tag @s add StonyPeaks
tag @s add StonyShore
tag @s add SunflowerPlains
tag @s add Swamp
tag @s add Taiga
tag @s add WarmOcean
tag @s add WindsweptForest
tag @s add WindsweptGravellyHills
tag @s add WindsweptHills
tag @s add WindsweptSavanna
tag @s add WoodedBadlands