scoreboard objectives add AdvancementCount dummy
scoreboard players remove @s[scores={AdvancementCount=1..}] AdvancementCount 1
scoreboard objectives add AdventureCount dummy
scoreboard players remove @s[scores={AdventureCount=1..}] AdventureCount 1
tag @s remove AdventuringTime
tag @s remove Badlands
tag @s remove BambooJungle
tag @s remove Beach
tag @s remove BirchForest
tag @s remove CherryGrove
tag @s remove ColdOcean
tag @s remove DarkForest
tag @s remove DeepColdOcean
tag @s remove DeepDark
tag @s remove DeepFrozenOcean
tag @s remove DeepLukewarmOcean
tag @s remove DeepOcean
tag @s remove Desert
tag @s remove DripstoneCaves
tag @s remove ErodedBadlands
tag @s remove FlowerForest
tag @s remove Forest
tag @s remove FrozenOcean
tag @s remove FrozenPeaks
tag @s remove FrozenRiver
tag @s remove Grove
tag @s remove IceSpikes
tag @s remove JaggedPeaks
tag @s remove Jungle
tag @s remove LukewarmOcean
tag @s remove LushCaves
tag @s remove MangroveSwamp
tag @s remove Meadow
tag @s remove MushroomFields
tag @s remove Ocean
tag @s remove OldGrowthBirchForest
tag @s remove OldGrowthPineTaiga
tag @s remove OldGrowthSpruceTaiga
tag @s remove Plains
tag @s remove River
tag @s remove Savanna
tag @s remove SavannaPlateau
tag @s remove SnowyBeach
tag @s remove SnowyPlains
tag @s remove SnowySlopes
tag @s remove SnowyTaiga
tag @s remove SparseJungle
tag @s remove StonyPeaks
tag @s remove StonyShore
tag @s remove SunflowerPlains
tag @s remove Swamp
tag @s remove Taiga
tag @s remove WarmOcean
tag @s remove WindsweptForest
tag @s remove WindsweptGravellyHills
tag @s remove WindsweptHills
tag @s remove WindsweptSavanna
tag @s remove WoodedBadlands