tellraw @s {"rawtext":[{"text":"§6==========================§r§§§bMonsters Hunted :§r§§§6==========================§r§§ "}]}
tellraw @s {"rawtext":[{"text":"§c[ INCOMPLETE ]§r"}]}
tellraw @s[tag=!Killed_Blaze] {"rawtext":[{"text":"Blaze"}]}
tellraw @s[tag=!Killed_Breeze] {"rawtext":[{"text":"Breeze"}]}
tellraw @s[tag=!Killed_Bogged] {"rawtext":[{"text":"Bogged"}]}
tellraw @s[tag=!Killed_CaveSpider] {"rawtext":[{"text":"Cave Spider"}]}
tellraw @s[tag=!Killed_Creaking] {"rawtext":[{"text":"Creaking / Creaking Heart"}]}
tellraw @s[tag=!Killed_Creeper] {"rawtext":[{"text":"Creeper"}]}
tellraw @s[tag=!Killed_Drowned] {"rawtext":[{"text":"Drowned"}]}
tellraw @s[tag=!Killed_ElderGuardian] {"rawtext":[{"text":"Elder Guardian"}]}
tellraw @s[tag=!Killed_Enderman] {"rawtext":[{"text":"Enderman"}]}
tellraw @s[tag=!Killed_Endermite] {"rawtext":[{"text":"Endermite"}]}
tellraw @s[tag=!Killed_EnderDragon] {"rawtext":[{"text":"Ender Dragon"}]}
tellraw @s[tag=!Killed_Evoker] {"rawtext":[{"text":"Evoker"}]}
tellraw @s[tag=!Killed_Ghast] {"rawtext":[{"text":"Ghast"}]}
tellraw @s[tag=!Killed_Guardian] {"rawtext":[{"text":"Guardian"}]}
tellraw @s[tag=!Killed_Hoglin] {"rawtext":[{"text":"Hoglin"}]}
tellraw @s[tag=!Killed_Husk] {"rawtext":[{"text":"Husk"}]}
tellraw @s[tag=!Killed_MagmaCube] {"rawtext":[{"text":"Magma Cube"}]}
tellraw @s[tag=!Killed_Phantom] {"rawtext":[{"text":"Phantom"}]}
tellraw @s[tag=!Killed_Piglin] {"rawtext":[{"text":"Piglin"}]}
tellraw @s[tag=!Killed_PiglinBrute] {"rawtext":[{"text":"Piglin Brute"}]}
tellraw @s[tag=!Killed_Pillager] {"rawtext":[{"text":"Golden Pillager"}]}
tellraw @s[tag=!Killed_Ravager] {"rawtext":[{"text":"Ravager"}]}
tellraw @s[tag=!Killed_Shulker] {"rawtext":[{"text":"Shulker"}]}
tellraw @s[tag=!Killed_Silverfish] {"rawtext":[{"text":"Silverfish"}]}
tellraw @s[tag=!Killed_Skeleton] {"rawtext":[{"text":"Skeleton"}]}
tellraw @s[tag=!Killed_Slime] {"rawtext":[{"text":"Slime"}]}
tellraw @s[tag=!Killed_Spider] {"rawtext":[{"text":"Spider"}]}
tellraw @s[tag=!Killed_Stray] {"rawtext":[{"text":"Stray"}]}
tellraw @s[tag=!Killed_Vex] {"rawtext":[{"text":"Vex"}]}
tellraw @s[tag=!Killed_Vindicator] {"rawtext":[{"text":"Vindicator"}]}
tellraw @s[tag=!Killed_Witch] {"rawtext":[{"text":"Witch"}]}
tellraw @s[tag=!Killed_Wither] {"rawtext":[{"text":"The Wither"}]}
tellraw @s[tag=!Killed_WitherSkeleton] {"rawtext":[{"text":"Wither Skeleton"}]}
tellraw @s[tag=!Killed_Zoglin] {"rawtext":[{"text":"Zoglin"}]}
tellraw @s[tag=!Killed_Zombie] {"rawtext":[{"text":"Zombie"}]}
tellraw @s[tag=!Killed_ZombieVillager] {"rawtext":[{"text":"Zombie Villager"}]}
tellraw @s[tag=!Killed_ZombifiedPiglin] {"rawtext":[{"text":"Zombified Piglin"}]}