execute as @a[tag=!StoneAge,hasitem={item=cobblestone}] run function adv/stone_age/grant
execute as @a[tag=!StoneAge,hasitem={item=cobbled_deepslate}] run function adv/stone_age/grant
execute as @a[tag=!StoneAge,hasitem={item=blackstone}] run function adv/stone_age/grant
execute as @a[tag=!GettingUpgrade,hasitem={item=stone_pickaxe}] run function adv/getting_an_upgrade/grant
execute as @a[tag=!AcquireHardware,hasitem={item=iron_ingot}] run function adv/acquire_hardware/grant
execute as @a[tag=!SuitUp,hasitem={item=iron_helmet}] run function adv/suit_up/grant
execute as @a[tag=!SuitUp,hasitem={item=iron_chestplate}] run function adv/suit_up/grant
execute as @a[tag=!SuitUp,hasitem={item=iron_leggings}] run function adv/suit_up/grant
execute as @a[tag=!SuitUp,hasitem={item=iron_boots}] run function adv/suit_up/grant
execute as @a[tag=!HotStuff,hasitem={item=lava_bucket}] run function adv/hot_stuff/grant
execute as @a[tag=!IronPick,hasitem={item=iron_pickaxe}] run function adv/isnt_it_iron_pick/grant
execute as @a[tag=!IceBucket,hasitem={item=obsidian}] run function adv/ice_bucket_challenge/grant
execute as @a[tag=!Diamonds,hasitem={item=diamond}] run function adv/diamonds/grant
execute as @a[tag=!CoverDiamonds,hasitem={item=diamond_helmet}] run function adv/cover_me_with_diamonds/grant
execute as @a[tag=!CoverDiamonds,hasitem={item=diamond_chestplate}] run function adv/cover_me_with_diamonds/grant
execute as @a[tag=!CoverDiamonds,hasitem={item=diamond_leggings}] run function adv/cover_me_with_diamonds/grant
execute as @a[tag=!CoverDiamonds,hasitem={item=diamond_boots}] run function adv/cover_me_with_diamonds/grant
execute as @a[tag=!Enchanter,hasitem={item=enchanting_table}] run function adv/enchanter/grant
execute as @a[tag=!HiddenDepths,hasitem={item=ancient_debris}] run function adv/hidden_in_the_depths/grant
execute as @a[tag=!CuttingOnions,hasitem={item=crying_obsidian}] run function adv/who_is_cutting_onions/grant
execute as @a[tag=!WarPigs,hasitem={item=netherite_upgrade_smithing_template}] run function adv/war_pigs/grant
execute as @a[tag=!CountryLode,hasitem={item=lodestone_compass}] run function adv/country_lode_take_me_home/grant
execute as @a[tag=!CoverDebris,hasitem=[{item=netherite_helmet},{item=netherite_chestplate},{item=netherite_leggings},{item=netherite_boots}]] run function adv/cover_me_in_debris/grant
execute as @a[tag=!SpookySkeleton,hasitem={item=skull,data=1}] run function adv/spooky_scary_skeleton/grant
execute as @a[tag=!IntoFire,hasitem={item=blaze_rod}] run function adv/into_fire/grant
execute as @a[tag=!NotNine,hasitem={item=respawn_anchor}] run function adv/not_quite_nine_lives/grant
execute as @a[tag=!LocalBrewery,hasitem={item=brewing_stand}] run function adv/local_brewery/grant
execute as @a[tag=!BringBeacon,hasitem={item=beacon}] run function adv/bring_home_the_beacon/grant
execute as @a[tag=!NextGeneration,hasitem={item=dragon_egg}] run function adv/the_next_generation/grant
execute as @a[tag=!NeedMint,hasitem={item=dragon_breath}] run function adv/you_need_a_mint/grant
execute as @a[tag=!SkyLimit,hasitem={item=elytra}] run function adv/skys_the_limit/grant
execute as @a[tag=!CraftLook,hasitem={item=bolt_armor_trim_smithing_template}] run function adv/crafting_a_new_look/grant
execute as @a[tag=!CraftLook,hasitem={item=coast_armor_trim_smithing_template}] run function adv/crafting_a_new_look/grant
execute as @a[tag=!CraftLook,hasitem={item=dune_armor_trim_smithing_template}] run function adv/crafting_a_new_look/grant
execute as @a[tag=!CraftLook,hasitem={item=eye_armor_trim_smithing_template}] run function adv/crafting_a_new_look/grant
execute as @a[tag=!CraftLook,hasitem={item=flow_armor_trim_smithing_template}] run function adv/crafting_a_new_look/grant
execute as @a[tag=!CraftLook,hasitem={item=host_armor_trim_smithing_template}] run function adv/crafting_a_new_look/grant
execute as @a[tag=!CraftLook,hasitem={item=raiser_armor_trim_smithing_template}] run function adv/crafting_a_new_look/grant
execute as @a[tag=!CraftLook,hasitem={item=rib_armor_trim_smithing_template}] run function adv/crafting_a_new_look/grant
execute as @a[tag=!CraftLook,hasitem={item=sentry_armor_trim_smithing_template}] run function adv/crafting_a_new_look/grant
execute as @a[tag=!CraftLook,hasitem={item=shaper_armor_trim_smithing_template}] run function adv/crafting_a_new_look/grant
execute as @a[tag=!CraftLook,hasitem={item=silence_armor_trim_smithing_template}] run function adv/crafting_a_new_look/grant
execute as @a[tag=!CraftLook,hasitem={item=snout_armor_trim_smithing_template}] run function adv/crafting_a_new_look/grant
execute as @a[tag=!CraftLook,hasitem={item=spire_armor_trim_smithing_template}] run function adv/crafting_a_new_look/grant
execute as @a[tag=!CraftLook,hasitem={item=tide_armor_trim_smithing_template}] run function adv/crafting_a_new_look/grant
execute as @a[tag=!CraftLook,hasitem={item=vex_armor_trim_smithing_template}] run function adv/crafting_a_new_look/grant
execute as @a[tag=!CraftLook,hasitem={item=ward_armor_trim_smithing_template}] run function adv/crafting_a_new_look/grant
execute as @a[tag=!CraftLook,hasitem={item=wayfinder_armor_trim_smithing_template}] run function adv/crafting_a_new_look/grant
execute as @a[tag=!CraftLook,hasitem={item=wild_armor_trim_smithing_template}] run function adv/crafting_a_new_look/grant
execute as @a[tag=!RespectingRemnants,hasitem={item=angler_pottery_sherd}] run function adv/respecting_the_remnants/grant
execute as @a[tag=!RespectingRemnants,hasitem={item=archer_pottery_sherd}] run function adv/respecting_the_remnants/grant
execute as @a[tag=!RespectingRemnants,hasitem={item=arms_up_pottery_sherd}] run function adv/respecting_the_remnants/grant
execute as @a[tag=!RespectingRemnants,hasitem={item=blade_pottery_sherd}] run function adv/respecting_the_remnants/grant
execute as @a[tag=!RespectingRemnants,hasitem={item=brewer_pottery_sherd}] run function adv/respecting_the_remnants/grant
execute as @a[tag=!RespectingRemnants,hasitem={item=burn_pottery_sherd}] run function adv/respecting_the_remnants/grant
execute as @a[tag=!RespectingRemnants,hasitem={item=danger_pottery_sherd}] run function adv/respecting_the_remnants/grant
execute as @a[tag=!RespectingRemnants,hasitem={item=explorer_pottery_sherd}] run function adv/respecting_the_remnants/grant
execute as @a[tag=!RespectingRemnants,hasitem={item=friend_pottery_sherd}] run function adv/respecting_the_remnants/grant
execute as @a[tag=!RespectingRemnants,hasitem={item=heart_pottery_sherd}] run function adv/respecting_the_remnants/grant
execute as @a[tag=!RespectingRemnants,hasitem={item=heartbreak_pottery_sherd}] run function adv/respecting_the_remnants/grant
execute as @a[tag=!RespectingRemnants,hasitem={item=howl_pottery_sherd}] run function adv/respecting_the_remnants/grant
execute as @a[tag=!RespectingRemnants,hasitem={item=miner_pottery_sherd}] run function adv/respecting_the_remnants/grant
execute as @a[tag=!RespectingRemnants,hasitem={item=mourner_pottery_sherd}] run function adv/respecting_the_remnants/grant
execute as @a[tag=!RespectingRemnants,hasitem={item=plenty_pottery_sherd}] run function adv/respecting_the_remnants/grant
execute as @a[tag=!RespectingRemnants,hasitem={item=prize_pottery_sherd}] run function adv/respecting_the_remnants/grant
execute as @a[tag=!RespectingRemnants,hasitem={item=sheaf_pottery_sherd}] run function adv/respecting_the_remnants/grant
execute as @a[tag=!RespectingRemnants,hasitem={item=shelter_pottery_sherd}] run function adv/respecting_the_remnants/grant
execute as @a[tag=!RespectingRemnants,hasitem={item=skull_pottery_sherd}] run function adv/respecting_the_remnants/grant
execute as @a[tag=!RespectingRemnants,hasitem={item=snort_pottery_sherd}] run function adv/respecting_the_remnants/grant
execute as @a[tag=!SmithingStyle,hasitem=[{item=spire_armor_trim_smithing_template},{item=snout_armor_trim_smithing_template},{item=rib_armor_trim_smithing_template},{item=ward_armor_trim_smithing_template},{item=vex_armor_trim_smithing_template},{item=silence_armor_trim_smithing_template},{item=tide_armor_trim_smithing_template}]] run function adv/smithing_with_style/grant
execute as @a[tag=!CarefulRestoration,hasitem={item=decorated_pot}] run function adv/careful_restoration/grant
execute as @a[tag=!BeeGuest,hasitem={item=honey_bottle}] run function adv/bee_our_guest/grant
execute as @a[tag=!TotalBeelocation,hasitem={item=bee_nest}] run function adv/total_beelocation/grant
execute as @a[tag=!BukkitBukkit,hasitem={item=tadpole_bucket}] run function adv/bukkit_bukkit/grant
execute as @a[tag=!SmellsInteresting,hasitem={item=sniffer_egg}] run function adv/smells_interesting/grant
execute as @a[tag=!TacticalFishing,hasitem={item=cod_bucket}] run function adv/tactical_fishing/grant
execute as @a[tag=!TacticalFishing,hasitem={item=salmon_bucket}] run function adv/tactical_fishing/grant
execute as @a[tag=!TacticalFishing,hasitem={item=pufferfish_bucket}] run function adv/tactical_fishing/grant
execute as @a[tag=!TacticalFishing,hasitem={item=tropical_fish_bucket}] run function adv/tactical_fishing/grant
execute as @a[tag=!SeriousDedication,hasitem={item=netherite_hoe}] run function adv/serious_dedication/grant
execute as @a[tag=!CutestPredator,hasitem={item=axolotl_bucket}] run function adv/the_cutest_predator/grant
execute as @a[tag=!PowersCombined,hasitem=[{item=verdant_froglight},{item=ochre_froglight},{item=pearlescent_froglight}]] run function adv/with_our_powers_combined/grant
execute as @a[tag=!MagicHappens,hasitem={item=adv:book_of_advancements}] run function adv/where_the_magic_happens/grant
execute as @a[tag=!WildWorld,hasitem=[{item=oak_sapling},{item=spruce_sapling},{item=birch_sapling},{item=jungle_sapling},{item=acacia_sapling},{item=dark_oak_sapling},{item=mangrove_propagule},{item=cherry_sapling},{item=pale_oak_sapling}]] run function adv/a_wild_world/grant
execute as @a[tag=!FruitLoom,hasitem={item=mojang_banner_pattern}] run function adv/fruit_on_the_loom/grant
execute as @a[tag=!SpeakTrees,hasitem={item=creaking_heart}] run function adv/i_speak_for_the_trees/grant
execute as @a[tag=!PureHeart,hasitem={item=resin_clump}] run function adv/pure_of_heart/grant
execute as @a[tag=!ChefsBliss,hasitem=[{item=oakridge:apple_pie},{item=oakridge:blazing_kebab},{item=oakridge:chorus_pie},{item=oakridge:cinnamon_roll},{item=oakridge:golden_apple_pie},{item=oakridge:meal},{item=oakridge:miners_stew},{item=oakridge:notch_apple_pie},{item=oakridge:sandwich_beef},{item=oakridge:sandwich_chicken},{item=oakridge:sandwich_fish},{item=oakridge:sandwich_mutton},{item=oakridge:sandwich_pork},{item=oakridge:sandwich_rabbit},{item=oakridge:sandwich_salmon},{item=oakridge:sweet_berry_pie}]] run function adv/chefs_bliss/grant